### ISSUE TITLE
take to long to create rarity

### ISSUE THREAD

**Issue by sadun619** [bolshoytoster/hashlips_art_engine#12]
### Checklist

- [X] I have read [COMMON_ISSUES.md](https://github.com/HashLips/hashlips_art_engine/blob/main/COMMON_ISSUES.md)
- [X] I have [searched existing issues](https://github.com/HashLips/hashlips_art_engine/issues?q=is%3Aissue)

### Description

if have many conditions (multiple different layerConfigurations) , it take too many time to create rarity, in my layer configuration have 143 configurations. and i'm waiting from 6 hours. but still not create rarity or not showing any error.  

### Environment

OS Version (`uname -a` on unix, `systeminfo` on windows):
Node.js version (`node -v`):

**Comment by bolshoytoster** [comment]
@sadun619 it's probably either stuck in a loop or you have a big collection.

Could you add `console.log(1)` on line 18, `console.log(2)` on line 43 and `console.log(3)` on line 60; then try to do rarity again and paste the output here please.

**Comment by sadun619** [comment]
> @sadun619 it's probably either stuck in a loop or you have a big collection.
> 
> Could you add `console.log(1)` on line 18, `console.log(2)` on line 43 and `console.log(3)` on line 60; then try to do rarity again and paste the output here please.

collection are 4489. but too may configurations, layers and traits have, (113 layer configuration, 65 layers, 876 traits)


i tried adding console.log, still take too may time time and no any respond. 

PS D:\Project\NFT_project\09-15-07-2022 4489\hashlips_art_engine-main> node utils/rarity.js
1

(process:13652): GLib-GIO-WARNING **: 22:29:13.560: Unexpectedly, UWP app `Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe' (AUMId `Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic') supports 20 extensions but has no verbs

**Comment by bolshoytoster** [comment]
@sadun619 what if you add `console.log('config')` on line 21, `console.log('layer')` after line 22 and `console.log('element')` after line 27.

**Comment by bolshoytoster** [comment]
@sadun619
> try with previous added console.log + new console.log and just new console.log both not working and both showing just word "element" and "layer" like as bellow .

It's not meant to make it work; I'm just trying to figure out what's wrong.

Does it continue outputting or does it stop after that `layer`?

**Comment by sadun619** [comment]
stop after layer

**Comment by sadun619** [comment]
> @sadun619
> 
> > try with previous added console.log + new console.log and just new console.log both not working and both showing just word "element" and "layer" like as bellow .
> 
> It's not meant to make it work; I'm just trying to figure out what's wrong.
> 
> Does it continue outputting or does it stop after that `layer`?

stop after layer. but i cant run another command on that terminal. at least cannot type. it stuck.

**Comment by bolshoytoster** [comment]
@sadun619
> i cant run another command on that terminal.

If you use `CTRL` + `C` you can interrupt the running command.

---

it looks like `getElements` is being really slow, it might have something to do with the warning you got.

[This comment](https://github.com/3b1b/manim/issues/1556#issuecomment-917456683) suggests running `Get-AppXPackage Microsoft.ZuneVideo -allusers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}` to get rid of it.

It may also be caused if you still have the command running in different terminals.

**Comment by sadun619** [comment]
> Get-AppXPackage Microsoft.ZuneVideo -allusers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

tried, warning still showing.

no. run only  one terminal.

**Comment by bolshoytoster** [comment]
@sadun619 could you try rebooting?

**Comment by bolshoytoster** [comment]
@sadun619 in `src/main.js` could you add `console.log(1)` after line 103 and `console.log(2)` after line 113?

**Comment by sadun619** [comment]
after modified main.js



Node.js v17.4.0
PS D:\Project\NFT_project\09-15-07-2022 4489\hashlips_art_engine-main> node utils/rarity.js
1
config
layer
1
2
D:\Project\NFT_project\09-15-07-2022 4489\hashlips_art_engine-main\src\main.js:115
    .forEach((i, index) => {
    ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at getElements (D:\Project\NFT_project\09-15-07-2022 4489\hashlips_art_engine-main\src\main.js:115:5)
    at D:\Project\NFT_project\09-15-07-2022 4489\hashlips_art_engine-main\utils\rarity.js:26:20
    at Array.forEach (<anonymous>)
    at D:\Project\NFT_project\09-15-07-2022 4489\hashlips_art_engine-main\utils\rarity.js:21:10
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\Project\NFT_project\09-15-07-2022 4489\hashlips_art_engine-main\utils\rarity.js:19:21)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Comment by bolshoytoster** [comment]
@sadun619 could you paste lines 112-117 of your `src/main.js` please.
